Repository PROJECT-NEXUS-JS/Backend, pull requests merged in 2025-08, with the labels that each got.

#25 ENHANCEMENT/#18 : open-in-view: false 반영 yml 수정
  src/main/resources/application.yml
Labels: enhancement

#32 hotfix#2 : FE CORS 요구사항 반영
  src/main/java/com/example/nexus/app/global/security/SecurityConfig.java
Labels: fix

#38 Feat/#35 프로필 관련 API 및 메시지 API
  src/main/java/com/example/nexus/app/global/code/status/ErrorStatus.java
  src/main/java/com/example/nexus/app/global/config/AsyncConfig.java
  src/main/java/com/example/nexus/app/message/controller/MessageController.java
  src/main/java/com/example/nexus/app/message/controller/dto/request/MessageSendRequest.java
  src/main/java/com/example/nexus/app/message/controller/dto/response/MessageFileInfo.java
  src/main/java/com/example/nexus/app/message/controller/dto/response/MessageResponse.java
  src/main/java/com/example/nexus/app/message/controller/dto/response/MessageRoomResponse.java
  src/main/java/com/example/nexus/app/message/controller/dto/response/MessageSenderInfo.java
  src/main/java/com/example/nexus/app/message/controller/dto/response/RoomPostInfo.java
  src/main/java/com/example/nexus/app/message/controller/dto/response/RoomUserInfo.java
  src/main/java/com/example/nexus/app/message/controller/dto/response/TodayMessageResponse.java
  src/main/java/com/example/nexus/app/message/domain/Message.java
  src/main/java/com/example/nexus/app/message/domain/MessageRoom.java
  src/main/java/com/example/nexus/app/message/domain/MessageType.java
  src/main/java/com/example/nexus/app/message/repository/MessageRepository.java
  src/main/java/com/example/nexus/app/message/repository/MessageRoomRepository.java
  src/main/java/com/example/nexus/app/message/service/MessageService.java
  src/main/java/com/example/nexus/app/recruitment/controller/RecruitmentProfileController.java
  src/main/java/com/example/nexus/app/recruitment/controller/dto/request/RecruitmentProfileUpdateRequest.java
  src/main/java/com/example/nexus/app/recruitment/controller/dto/response/RecruitmentProfileResponse.java
  src/main/java/com/example/nexus/app/recruitment/domain/RecruitmentProfile.java
  src/main/java/com/example/nexus/app/recruitment/repository/RecruitmentProfileRepository.java
  src/main/java/com/example/nexus/app/recruitment/service/RecruitmentProfileService.java
  src/main/java/com/example/nexus/app/user/domain/User.java
Labels: ✨FEAT

#39 Feat/#21 실시간 랭킹 페이지 API 구현
  src/main/java/com/example/nexus/app/post/repository/PostRepository.java
  src/main/java/com/example/nexus/app/ranking/controller/RankingController.java
  src/main/java/com/example/nexus/app/ranking/dto/FullRankingResponse.java
  src/main/java/com/example/nexus/app/ranking/dto/HomeRankingResponse.java
  src/main/java/com/example/nexus/app/ranking/repository/RankingRepository.java
  src/main/java/com/example/nexus/app/ranking/service/RankingService.java
  src/main/java/com/example/nexus/app/user/controller/UserInterestController.java
  src/main/java/com/example/nexus/app/user/domain/UserInterest.java
  src/main/java/com/example/nexus/app/user/dto/UserInterestDto.java
  src/main/java/com/example/nexus/app/user/repository/UserInterestRepository.java
  src/main/java/com/example/nexus/app/user/service/UserInterestService.java
Labels: ✨FEAT

#40 Feat/#8 상세페이지 뷰 구현 3가지
  src/main/java/com/example/nexus/app/post/controller/PostController.java
  src/main/java/com/example/nexus/app/post/controller/dto/response/PostMainViewDetailResponse.java
  src/main/java/com/example/nexus/app/post/controller/dto/response/PostRightSidebarResponse.java
  src/main/java/com/example/nexus/app/post/controller/dto/response/SimilarPostResponse.java
  src/main/java/com/example/nexus/app/post/service/PostService.java
Labels: ✨FEAT

#45 feat/#43: 개인정보 항목 필드 수정 및 개인정보 항목 조회 API 구현
  src/main/java/com/example/nexus/app/post/controller/ParticipationController.java
  src/main/java/com/example/nexus/app/post/controller/dto/request/ParticipationApplicationRequest.java
  src/main/java/com/example/nexus/app/post/controller/dto/request/PostCreateRequest.java
  src/main/java/com/example/nexus/app/post/controller/dto/request/PostUpdateRequest.java
  src/main/java/com/example/nexus/app/post/controller/dto/response/ParticipantPrivacyResponse.java
  src/main/java/com/example/nexus/app/post/controller/dto/response/ParticipationResponse.java
  src/main/java/com/example/nexus/app/post/controller/dto/response/PostFeedbackResponse.java
  src/main/java/com/example/nexus/app/post/domain/Participation.java
  src/main/java/com/example/nexus/app/post/domain/PostFeedback.java
  src/main/java/com/example/nexus/app/post/domain/PrivacyItem.java
  src/main/java/com/example/nexus/app/post/domain/dto/ParticipationApplicationDto.java
  src/main/java/com/example/nexus/app/post/repository/ParticipationRepository.java
  src/main/java/com/example/nexus/app/post/repository/PostFeedbackRepository.java
  src/main/java/com/example/nexus/app/post/service/ParticipationService.java
  src/main/java/com/example/nexus/app/post/service/PostService.java
Labels: ✨FEAT

#49 hotfix/#48: 비로그인 사용자 게시글 목록 볼 수 있게 수정
  src/main/java/com/example/nexus/app/global/security/SecurityConfig.java
  src/main/java/com/example/nexus/app/post/controller/PostController.java
  src/main/java/com/example/nexus/app/post/service/PostService.java
Labels: fix

#61 Fix/#60 : LazyLoadingException 수정
  src/main/java/com/example/nexus/app/review/controller/ReviewController.java
  src/main/java/com/example/nexus/app/review/repository/ReviewRepository.java
  src/main/java/com/example/nexus/app/review/service/ReviewService.java
Labels: fix

#65 update/#63: platformCategory 필수값 해제
  src/main/java/com/example/nexus/app/post/domain/Post.java
Labels: update

#71 fix/#70: 전일 조회수 비교 및 선형차트 조회수 로직 오류 수정
  src/main/java/com/example/nexus/app/dashboard/domain/scheduler/RedisViewCountScheduler.java
  src/main/java/com/example/nexus/app/post/service/ViewCountService.java
Labels: fix

#76 fix/#70: 게시글 조회수 로직 수정
  src/main/java/com/example/nexus/app/dashboard/domain/scheduler/RedisViewCountScheduler.java
  src/main/java/com/example/nexus/app/post/domain/Post.java
  src/main/java/com/example/nexus/app/post/repository/PostRepository.java
  src/main/java/com/example/nexus/app/post/service/ViewCountService.java
Labels: fix

#79 fix/#78: 로그아웃시 토큰 블랙리스트 처리
  src/main/java/com/example/nexus/app/global/oauth/controller/AuthController.java
  src/main/java/com/example/nexus/app/global/oauth/service/AuthService.java
  src/main/java/com/example/nexus/app/global/security/JwtAuthenticationProcessingFilter.java
Labels: bug

#90 fix/#89: 게시글 상세보기 수정
  src/main/java/com/example/nexus/app/post/domain/PostContent.java
Labels: fix

#94 fix/#93: 테스트 참여 승인 로직 수정
  src/main/java/com/example/nexus/notification/domain/Notification.java
Labels: fix

#97 fix/#96: 참가 신청자 조회 로직 수정
  src/main/java/com/example/nexus/app/post/repository/ParticipationRepository.java
Labels: fix
